# 配置文件
ThreadCount=32
RetryCount=3
Timeout=10
SaveDir="/Users/rumikr/Downloads/cp/N_m3u8DL-RE_ShellGUI_macOS-main/downloads"
TempDir="/Users/rumikr/Downloads/cp/N_m3u8DL-RE_ShellGUI_macOS-main/temp"
Language=zh-CN
LogLevel=INFO
AutoSelect=true
ConcurrentDownload=true
RealTimeDecryption=true
CheckSegments=true
DeleteAfterDone=false
WriteMetaJson=true
AppendUrlParams=true
